---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: game-service-secret
  namespace: microservice-app-staging
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    JWT_SECRET_KEY: AgBp+FsUFkOgQvO5o3smYQs3mMZywlUhRqVxbfOrFequbafHm9+2taM+tvj5h4zGQdKmfQFNszHwz23/dkPsD5rwuZtQ5sRBBHa5AVJlHzYyPY+tfyi/scF+PjrPISLK/xAqz/m7MZuqEtEhTb2iaav6mkkBfx9M2My4Re35raUmgBlUY45KQiRVgn0eaop3nCHWTQg2DtAMraM0jMDtQxOJ8y+lS/ndnOcsfSq6dN7/fEv1faog7gp+ybmt7KxsHd34HTDyVMYPEBWLN3WmcfKYXJjz0mTEx/WAXhoyL8twlvO9SMuBBsLKCF4JCXcgFMXJ2fX0RrZFkG2Opc0eZnMxouAb3rODF/2nvpa1aV3XmqEusf1clXIftrUSYwje1Lp8FwiZgiPfrPLUYv+NxfIg/qhUkYfEXr4heWLefdb9SUTZ3vYJAQDK6PtWQXptXcgjKj/LG/iu6GdQvXyeLpMtloYN1hptZX1hYYOBS7nC6hjj8HcctpdB2/ll9SNIv5sb9s2R47dy4hTDei321m4zB7DzTQRSv5W0z8enPCdxSt8pEG+jPHkHfoWzOW4dSoyVEYEOe7qa4g75cX1U3PgqJ2GAdeg57aoP1y3aOAGH+MmgkxZtoFBdFWpQfI/qwsLVK/hNep2zQg4I66rI0aaWa4SoGlBkSTlbvK/Vpmx6lQnlRidl117p/YU5hxV33fQYd4QefrguXIr0NwaTX+bTnYgQKQFBCcdQ2KXE0+2gT1rcomj8e9ogjfIrVA==
  template:
    metadata:
      name: game-service-secret
      namespace: microservice-app-staging
    type: Opaque
