apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eks-sealed-secrets
  namespace: openshift-gitops  # ArgoCD runs here on OpenShift
  labels:
    app.kubernetes.io/part-of: cluster-bootstrap
    app.kubernetes.io/component: secret-management
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: 2.16.1
    helm:
      releaseName: sealed-secrets
      values: |
        fullnameOverride: sealed-secrets-controller
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi

  destination:
    server: https://D20887DF69A3E32BEDBFB7E9B9E2398C.gr7.us-east-1.eks.amazonaws.com
    namespace: sealed-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
