apiVersion: v1
kind: Namespace
metadata:
  name: microservice-app-prod
  labels:
    app.kubernetes.io/part-of: microservice-app
    environment: prod
    cluster: eks
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
