---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: auth-service-secret
  namespace: microservice-app-prod
spec:
  encryptedData:
    JWT_SECRET_KEY: AgBzzaIUAPKGKkHwL4QcSm5Cy+IVRQiShNvDWxrYJREcwVvvzXcvIN6vKiiJ7xwbvuV4RVufOToqPaFmFumnyUmIoA2rjJ8bEM5iEVbLS6cMGpL9YJes7K9cDAY9QULJaoQ+Pw3xM6tMcFseF+a5JgUgGHoqI6WM8o/Qm8jpD+utusiI/VT4xwITHK5YzqJgY8mVJFlU/5J7yYVOEkx4Y+WJZD3yOLvi00xVPMIqlMbPS717c35tclfg/GJbjM3O5dzXqaoPfWwnn6VZ5oWf+e4Ejy39j5JapFrjlk0A6TYOrQ707QPNIHZgoCPFxqDRGjwsRKWInN0831i4O7J9ViiBxm3Sudidfe6/4846L9n0xcf8BpMmGCG7HHhD6H/b6n2YB9pDJrVjuwBRITsKNL/OXSos9hGKR5efHOruSXWDMyvsitg1vYMfP+lrEyvOPlU4qhc1/YcfmqcwWDTyTpVGaK3NQVN4yHko0nrov1xJJVXUNLYwsS4+HkSUzDQtFKxsnX+/A29VK3YPt70Iy65bKnc4v1TymsnNmpQSLFCuQ84sVa04yso6QAqMEo02OS0iHauReIlZ+PcNSuM36YzDKhu3fS38I6Fi7GYy0YOa5bbb18LOR1xXMcC2TUPXgR+xwKknzAQR4eUQvSd16J7g7n0rn9q+bhQMBcQ6JKWleCvXvzzQs2cbvgIhT7xg9dBqS3R6QHsteQhrKxmZvCC+wD0xm3zT6E8zhZLhHb44gtKX8eBvlmNmKf0DUw==
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
      name: auth-service-secret
      namespace: microservice-app-prod
    type: Opaque
