---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: dockerhub-cred
  namespace: microservice-app-prod
spec:
  encryptedData:
    .dockerconfigjson: AgAbw0GRA9dsYTPebNesnwq73Sxurb1/pFXhO34qedJpd30/Ritd0rDCTh3SZ4MVOY1bkDfxXNQlVj2do1tnJcDyuMI+UyJOh2YQG1ZRN2p4yRLE2WczvmfHYMl4GMZ9qSSddWVMfQBqEGMeRA4Yt26A0GGENNKRtCcdiTm8ZFuLKXCQwaIMhrjYxdVdiLFTXzoUfkv22hl2ph9TzFat1GLlcan2znKdX7ByF3uRiVJodAVHv07bSzHmv3TGyqU3+EcCZRqtP6wYkjTGo7ozC6RT+GItH2q7m5w9QfD4WQwa/9fk7h3qjqHmOmICy5N10mLH74+iNeyZXcQKeaIpDwqAKpmUkR72/q1eKD1NEPgJNOVv4s27mor9TC0FM0/u77/MSF9DQ7+cRIWsSWnuQAAmtPFaVoTUppYFJ5pWSiZFBdwpBqRMUB9FzFjiTCl5YEumvn8hhds3WlPG19zSVPfCVjvXA+fo7Z6Jn3CdLj4xp2YL+McNPLI+mMuu+rsNGaLAKod++dAXOnPKOoLMRlQdAWsSEnaZLYSgfa1O69a6m2ykzNCW1evcfyRj+8pSmBH1dGWO8mzvOT4Xp8ifIxYVqkuFhQLaDoKaoSbKaOOrjL7ktq4aXFe1XNR1VUoPw98x/pshrFKJcqwTmQjZhogWQHERTndj8CvFTdf3UncGs5GWq29BzQpi5XNymutm1EYVk9G18Wb0sn14VbGgimuxItTJ9X8Rn09Es4PbWd7yEkyG8qGFRfGzylBZ3n1cgN3hyqwm2PjWJaVSsf85zw4tNpaGnqHptnuqRjIASbLQ6o+iwXs8axP6z2FNtN1G8P7yvmgtQyRVBr8PpT23hHstQheKiI+GmGXdhA==
  template:
    metadata:
      name: dockerhub-cred
      namespace: microservice-app-prod
    type: kubernetes.io/dockerconfigjson
