apiVersion: v1                    
kind: Secret          
metadata:                         
  name: game-service-secret
  namespace: microservice-app-prod   
type: Opaque
stringData:
  JWT_SECRET_KEY: "ZNcmCDdDlW0JUJgzWS16eBrFuY8/yB08V2fDPg+cUKw="
